services:
  db-dev:
    image: postgres:latest
    env_file:
      - .env.development
    ports:
      - "5432:5432"
    volumes:
      - db-dev-data:/var/lib/postgresql/data

  minio-dev:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env.development
    volumes:
      - minio-dev-data:/data
    command: server --console-address ":9001" /data

  keycloak-dev:
    image: quay.io/keycloak/keycloak:26.1.0
    ports:
      - "8080:8080"
    env_file:
      - .env.development
    command: ["start-dev"]
    volumes:
      - keycloak-dev-data:/opt/keycloak/data

volumes:
  db-dev-data:
  minio-dev-data:
  keycloak-dev-data:
