services:
  db-dev:
    image: postgres:latest
    env_file:
      - .env.development
    ports:
      - "5433:5432"
    volumes:
      - db-dev-data:/var/lib/postgresql/data

  minio-dev:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env.development
    volumes:
      - minio-dev-data:/data
    command: server --console-address ":9001" /data

  keycloak-dev:
    image: quay.io/keycloak/keycloak:26.1.0
    ports:
      - "8080:8080"
    env_file:
      - .env.development
    command: ["start-dev"]
    volumes:
      - keycloak-dev-data:/opt/keycloak/data

  mongo-dev:
    image: mongo
    env_file:
      - .env.development
    ports:
      - 27017:27017
    volumes:
      - mongo-dev-data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8081:2001
    env_file:
      - .env.development

  redis:
    image: bitnami/redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6378:6379"
    volumes:
      - "redis-dev-data:/bitnami/redis/data"

volumes:
  db-dev-data:
  minio-dev-data:
  keycloak-dev-data:
  mongo-dev-data:
  redis-dev-data:
