services:
  db-dev:
    image: postgres:latest
    env_file:
      - .env.development
    ports:
      - "5432:5432"
    volumes:
      - db-dev-data:/var/lib/postgresql/data

volumes:
  db-dev-data:
